---
- hosts: win
  vars:
   username: "{{ name1 }}"
   newpassword: "{{ newpass }}"
  tasks:
   - debug:
      msg: 
       - "{{ name1 }}"
       - "{{ newpass }}"
   - name: Reset the password through LDS
     win_shell: |
      [String]$username1 = "{{ username }}"  
      $sucess= Get-ADUser -Filter {(Name -eq $username1)} -SearchBase "CN=Partition1,DC=LDS1,DC=COM" -Server 'localhost:1026' 
      if($sucess)
      {
        $pass= "{{ newpassword }}"
        $newpass= ConvertTo-SecureString $pass -AsPlainText -Force
        Set-ADAccountPassword -Identity "CN=$username1,CN=Partition1,DC=LDS1,DC=COM" -Server ‘localhost:1026’   -NewPassword $newpass -Reset
      }
      