---
- hosts: win
  vars_prompt:
    - name: username
      prompt: "Enter your username (SAMAccountName):-"
      private: no
    - name: security1
      prompt: "SECURITY QUESTION-1: Enter your department:-"
      private: no
    - name: security2
      prompt: "SECURITY QUESTION-2: Enter your city:-"
      private: no
    - name: newpassword
      prompt: "Enter New Password:-"
      private: yes

  tasks:
   - name: Running Powershell Script in Windows host
     win_shell: | 
      $username= "{{ username }}" 
      $user_depart= "{{ security1 }}" 
      $user_city= "{{ security2 }}" 
      $newpass = "{{ newpassword }}" 

      $department=Get-ADUser -Filter "SamAccountName -eq '$username'" -SearchBase "DC=LTI_10668414,DC=COM" -Properties Department | Select-Object Department
      $city=Get-ADUser -Filter "SamAccountName -eq '$username'" -SearchBase "DC=LTI_10668414,DC=COM" -Properties city | Select-Object city
      if($department.Department -eq $user_depart -and $city.city -eq $user_city ){
       Set-ADAccountPassword -Identity $username -Reset -NewPassword (ConvertTo-SecureString -AsPlainText "$newPass" -Force)
      }


---
- hosts: win
  vars:
   username: "{{ user }}"
   security1: "{{ sec1 }}"
   security2: "{{ sec2 }}"
   newpassword: "{{ newpass }}"
      
  tasks:
   - name: Running Powershell Script in Windows host
     win_shell: | 
      $username= "{{ username }}" 
      $user_depart= "{{ security1 }}" 
      $user_city= "{{ security2 }}" 
      $newpass = "{{ newpassword }}" 

      $department=Get-ADUser -Filter "SamAccountName -eq '$username'" -SearchBase "DC=LTI_10668414,DC=COM" -Properties Department | Select-Object Department
      $city=Get-ADUser -Filter "SamAccountName -eq '$username'" -SearchBase "DC=LTI_10668414,DC=COM" -Properties city | Select-Object city
      if($department.Department -eq $user_depart -and $city.city -eq $user_city ){
       Set-ADAccountPassword -Identity $username -Reset -NewPassword (ConvertTo-SecureString -AsPlainText "$newPass" -Force)
      }

#Code Has been completed